using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Template.Game
{
    [GenerateTypedNameReferences]
    public sealed partial class GameBrowserWindow : SS14Window
    {
        public GameBrowserWindow()
        {
            RobustXamlLoader.Load(this);

            Browser.MouseFilter = MouseFilterMode.Stop;
            MouseFilter = MouseFilterMode.Pass;

            UrlBar.OnTextEntered += UrlBarOnOnTextEntered;
        }

        private void UrlBarOnOnTextEntered(LineEdit.LineEditEventArgs obj)
        {
            Browse(obj.Text);
        }

        public void Browse(string url)
        {
            Browser.Url = url;
        }
    }
}